site_name: Cartologic
site_url: http://www.cartologic.com/
repo_url: https://github.com/cartologic/cartoview
site_description: GIS Web Mapping Applications.Cartoview enables the rapid deployment of easy-to-manage and easy-to-use spatial web applications
copyright: Cartologic
site_author: Cartologic
remote_branch: master
remote_name: io
pages:
    -  Cartoview:
        - 'About': 'index.md'
        - 'Key Features': 'keys.md'
        - 'Demos': 'demo.md'
        - 'Frequently Asked Questions': 'QA.md'
        - 'Installation': 'installation.md'
        - 'Docker': 'docker.md'
        - 'Developers': 'developers.md'
        - 'Contribute': 'contrib.md'
        - 'Issues': 'issues.md'
        - 'Install App': 'market.md'

theme: 'material'
extra:
  palette:
    primary: 'blue'
    accent: 'indigo'
  font:
    text: 'PT Sans'
    code: 'Source Code Pro'
  
markdown_extensions:
  - admonition
  - footnotes
  - codehilite(linenums=true)
  - toc(permalink=true)
  - meta
  - pymdownx.superfences
  - pymdownx.tasklist(custom_checkbox=true)
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
